image:
  repository: ghcr.io/mlflow/mlflow
  tag: v2.14.1
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 5000
  name: mlflow

resources:
  limits:
    cpu: "500m"
    memory: "1Gi"
  requests:
    cpu: "100m"
    memory: "512Mi"

mlflow:
  host: "0.0.0.0"
  port: 5000
  backendStoreUri: "sqlite:///mlflow.db"
  defaultArtifactRoot: "/mlruns"

persistence:
  enabled: false
